book_collection/urls.py
from django.conf import settings
from django.conf.urls.static import static
"""
URL configuration for book_collection project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
] 

main/urls.py
from django.urls import path
from main.views import *


app_name = 'main'


urlpatterns = [
    path('', show_landing_page, name='show_landing_page'),
    path('main/', show_main, name='show_main'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),

    path('get-items/', get_item_json, name='get_item_json'),
    path('create-ajax/', add_item_ajax, name='create_ajax'),
    path('delete-ajax/', delete_item_ajax, name='delete_ajax'),
    path('add-stock/', add_stock_ajax, name='add_stock'),
    path('sub-stock/', sub_stock_ajax, name='sub_stock'),

    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),

    path('create-flutter/', create_item_flutter, name='create_item_flutter'),
    path('get-items-flutter/', get_item_flutter, name='get_item_flutter'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0"
    />
    <link
      rel="preconnect"
      href="https://fonts.googleapis.com"
    />
    <link
      rel="preconnect"
      href="https://fonts.gstatic.com"
      crossorigin
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap"
      rel="stylesheet"
    />
    <title>{% block title %} {% endblock title %}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="{% static 'css/style.css' %}"
      type="text/css"
    />
  </head>
  <body class="d-flex flex-column min-vh-100">
    <nav
      class="navbar navbar-expand bg-dark border-bottom border-body navbar-dark"
    >
      <div class="container-fluid">
        <a
          class="navbar-brand mb-0 h2 col fw-bold"
          href="{% url 'main:show_landing_page' %}"
          ><span role="img">📖</span>PBP Ganjil 23/24</a
        >
        <div class="col justify-content-center">
          <p class="navbar-brand mb-0 h1 text-center fw-bold">
            BOOK COLLECTION
          </p>
        </div>
        <div class="col">
          <ul class="navbar-nav container-fluid justify-content-end">
            {% block links %} 
            {% if user != AnonymousUser %}
              <li class="nav-item">
                <a
                  class="nav-link active"
                  href="{% url 'main:logout' %}"
                  ><span class="border-bottom border-light">Logout</span></a
                >
              </li>
              <li class="nav-item">
                <p class="navbar-text mb-0">
                  <span class="text-light me-2 ps-2 border-start border-light"
                    >Welcome, {{ user }}</span
                  >
                </p>
              </li>
              <li class="nav-item">
                <a
                  class="nav-link active"
                  href="{% url 'main:show_main' %}"
                  ><span class="border-bottom border-light">KoleksiKu</span></a
                >
              </li>
              <li class="nav-item">
                <button
                  type="button"
                  data-bs-toggle="modal"
                  data-bs-target="#modalAdd"
                  class="nav-link active"
                >
                  <span class="border-bottom border-light">Tambah Buku</span>
                </button>
              </li>
            {% else %}
              <li class="nav-item">
                <p class="navbar-text mb-0">
                  <span class="text-light">Welcome to Book Collection</span>
                </p>
              </li>
            {% endif %} 
            {% endblock links %}
          </ul>
          
          {% if last_login %}
          <div class="container justify-content-end text-end">
            <small class="text-light me-2">Last Login: {{ last_login }}</small>
          </div>
          {% endif %}
        </div>
      </div>
    </nav>

    {% block content %} {% endblock content %}

    <div class="container-fluid bg-dark mt-auto">
      <footer class="d-flex justify-content-center align-items-center py-3 m-0">
        <div class="col-md-4 d-flex align-items-center justify-content-center">
          <p class="mb-3 mb-md-0 text-light">
            &copy; 2023 Restu Ahmad Ar Ridho
          </p>
        </div>
      </footer>
    </div>

    <div
      class="modal fade"
      id="modalAdd"
      tabindex="-1"
      aria-labelledby="modalAddLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1
              class="modal-title fs-5"
              id="modalAddLabel"
            >
              Add New Book
            </h1>
            <button
              type="button"
              class="btn-close"
              data-bs-dismiss="modal"
              aria-label="Close"
            ></button>
          </div>
          <div class="modal-body">
            <form
              id="form-add-buku"
              onsubmit="return false;"
            >
              {% csrf_token %}
              <div class="mb-3">
                <label
                  for="name"
                  class="col-form-label"
                  >Name:</label
                >
                <input
                  type="text"
                  id="name"
                  name="name"
                  class="form-control"
                  placeholder="Title here..."
                  required
                  autofocus
                />
              </div>
              <div class="mb-3">
                <label
                  for="amount"
                  class="col-form-label"
                  >Amount:</label
                >
                <input
                  type="number"
                  class="form-control"
                  id="amount"
                  name="amount"
                  placeholder="1..."
                  required
                />
              </div>
              <div class="mb-3">
                <label
                  for="description"
                  class="col-form-label"
                  >Description:</label
                >
                <textarea
                  class="form-control"
                  id="description"
                  name="description"
                  placeholder="Description here..."
                ></textarea>
              </div>
            </form>
          </div>
          <div class="modal-footer">
            <button
              type="button"
              class="btn btn-secondary"
              data-bs-dismiss="modal"
            >
              Close
            </button>
            <button
              type="button"
              class="btn btn-dark"
              id="button_add"
              data-bs-dismiss="modal"
            >
              Add Book
            </button>
          </div>
        </div>
      </div>
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"
    ></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
    <script src="{% static 'js/index.js' %}"></script>
  </body>
</html>