book_collection/urls.py
from django.conf import settings
from django.conf.urls.static import static
"""
URL configuration for book_collection project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
] 

main/urls.py
from django.urls import path
from main.views import *


app_name = 'main'


urlpatterns = [
    path('', show_landing_page, name='show_landing_page'),
    path('main/', show_main, name='show_main'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),

    path('get-items/', get_item_json, name='get_item_json'),
    path('create-ajax/', add_item_ajax, name='create_ajax'),
    path('delete-ajax/', delete_item_ajax, name='delete_ajax'),
    path('add-stock/', add_stock_ajax, name='add_stock'),
    path('sub-stock/', sub_stock_ajax, name='sub_stock'),

    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),

    path('create-flutter/', create_item_flutter, name='create_item_flutter'),
    path('get-items-flutter/', get_item_flutter, name='get_item_flutter'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User


class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    amount = models.IntegerField()
    description = models.TextField()
    date_added = models.DateField(auto_now_add=True)

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "amount", "description"]

main/views.py
import datetime
import json

from django.http import HttpResponseRedirect, HttpResponse, HttpResponseNotFound, JsonResponse
from django.urls import reverse
from django.core import serializers
from django.shortcuts import render, redirect

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from django.views.decorators.csrf import csrf_exempt

from main.models import Item


@csrf_exempt
def create_item_flutter(request):
    if request.method == 'POST':

        data = json.loads(request.body)

        new_item = Item.objects.create(
            user=request.user,
            name=data["name"],
            amount=int(data["amount"]),
            description=data["description"]
        )

        new_item.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)


@csrf_exempt
def add_item_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        user = request.user

        new_item = Item(name=name, amount=amount,
                        description=description, user=user)
        new_item.save()

        return HttpResponse(f"Buku {name} dengan jumlah {amount} telah ditambahkan", status=201)

    return HttpResponseNotFound()


@csrf_exempt
def delete_item_ajax(request):
    data = json.loads(request.body.decode("utf-8"))
    item = Item.objects.get(pk=data["id"])
    item.delete()
    return HttpResponse("DELETED", status=200)


@csrf_exempt
def add_stock_ajax(request):
    data = json.loads(request.body.decode("utf-8"))
    item = Item.objects.get(pk=data["id"])
    item.amount += 1
    item.save()
    return HttpResponse(status=200)


@csrf_exempt
def sub_stock_ajax(request):
    data = json.loads(request.body.decode("utf-8"))
    item = Item.objects.get(pk=data["id"])
    if item.amount > 1:
        item.amount -= 1
        item.save()
    return HttpResponse(status=200)


def get_item_json(request):
    Items = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', Items))


def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(
                request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form': form}
    return render(request, 'register.html', context)


def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main"))
            response.set_cookie('user', user)
            response.set_cookie('last_login', str(
                datetime.datetime.now().strftime('%d-%m-%Y %H:%M')))
            return response
        else:
            messages.info(
                request, 'Sorry, incorrect username or password. Please try again.')
    return render(request, 'login.html')


def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:show_landing_page'))
    response.delete_cookie('last_login')
    response.delete_cookie('user')
    return response


def show_landing_page(request):
    user = request.COOKIES.get('user', None)

    context = {
        'name': 'Restu Ahmad Ar Ridho',  # Nama kamu
        'class': 'PBP E',  # Kelas PBP kamu
        'user': user,
    }

    return render(request, "index.html", context)


@login_required(login_url='/login')
def show_main(request):
    Items = Item.objects.filter(user=request.user)

    context = {
        'name': request.user.username,
        'data': Items,
        'last_login': request.COOKIES['last_login'],
        'user': request.COOKIES['user']
    }

    return render(request, "main.html", context)


# Mengembalikan data
def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")


def show_json(request):
    print(request.user)
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")


def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")


def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")


def get_item_flutter(request):

    print("========ID")
    print(request.user)
    print("========PK")
    print(request.user.pk)
    print("========")
    Items = Item.objects.filter(user=request.user.pk)
    return HttpResponse(serializers.serialize('json', Items))

main/templates/index.html
{% extends 'base.html' %} 

{% block title %} Homepage | Book Collection {%endblock title %} 

{% block content %}
<div class="px-4 py-5 my-5 text-center center">
  <h1 class="display-5 fw-bold">{{ name }} <br />{{ class }}</h1>
  <div class="col-lg-6 mx-auto">
    <p class="lead mb-4">
      Welcome to our Book Collection! We love books and have put together a
      variety of titles just for you. From classics to modern reads, there's
      something here for everyone. We hope you find the perfect book to enjoy.
    </p>
    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
      <a
        type="button"
        class="btn btn-dark btn-lg px-4 gap-3"
        href="{% url 'main:login' %}"
        >Login</a
      >
      <a
        type="button"
        class="btn btn-outline-secondary btn-lg px-4"
        href="{% url 'main:register' %}"
        >Sign Up</a
      >
    </div>
  </div>
</div>
{% endblock content %}

main/templates/landingpage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0"
    />
    <link
      rel="preconnect"
      href="https://fonts.googleapis.com"
    />
    <link
      rel="preconnect"
      href="https://fonts.gstatic.com"
      crossorigin
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap"
      rel="stylesheet"
    />
    <title>Book Collection</title>
    <style>
      * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        color: #ffffff;
      }

      body {
        font-family: "Poppins", sans-serif;
        background-color: #e3e3e6;
      }

      .nav-bar {
        display: grid;
        grid-template-columns: 1fr 1fr 1fr;
        align-items: center;
        height: 3.5rem;
        padding: 0 1rem;
        background-color: #000000;
      }

      .logo {
        display: flex;
        align-items: center;
        gap: 0.8rem;
      }

      a {
        text-decoration: none;
        font-weight: 600;
      }

      .logo span {
        font-size: 1.8rem;
        margin-top: -6px;
      }

      .header {
        justify-content: center;
        text-align: center;
        font-size: 2rem;
      }

      .links {
        justify-self: end;
      }

      .hero {
        text-align: center;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        gap: 1rem;
        height: calc(100vh - 7rem);
      }

      .hero h1 {
        color: #000000;
        font-size: 2.5rem;
      }

      .hero p {
        font-size: 1rem;
        color: #666;
        width: 40rem;
        margin-top: -1rem;
      }

      .cta-button {
        display: inline-block;
        padding: 0.7rem 1.5rem;
        background-color: #333;
        text-decoration: none;
        border-radius: 0.4rem;
      }

      footer {
        text-align: center;
        padding: 1rem;
        background-color: #000000;
      }
    </style>
  </head>
  <body>
    <nav class="nav-bar">
      <div class="logo">
        <span role="img">📖</span>
        <a href="/">PBP Ganjil 23/24</a>
      </div>
      <div>
        <h1 class="header">BOOK COLLECTION</h1>
      </div>
      <div class="links">
        <a href="/">Home</a>
      </div>
    </nav>

    <section class="hero">
      <h1>Restu Ahmad Ar Ridho <br />PBP - E</h1>
      <p>
        Welcome to our Book Collection! We love books and have put together a
        variety of titles just for you. From classics to modern reads, there's
        something here for everyone. We hope you find the perfect book to enjoy.
      </p>
      <a
        href="/main"
        class="cta-button"
        >Go to Collection</a
      >
    </section>
    <footer>
      <p>&copy; 2023 Restu Ahmad Ar Ridho</p>
    </footer>
  </body>
</html>

main/templates/login.html
{% extends 'base.html' %} 

{% block title %} Login | Book Collection {%endblock title %} 

{% block links %}
<li class="nav-item">
  <a
    class="nav-link active"
    href="{% url 'main:show_landing_page' %}"
    ><span class="border-bottom border-light">Home</span></a
  >
</li>
<li class="nav-item">
  <a
    class="nav-link active"
    href="{% url 'main:register' %}"
    ><span class="border-bottom border-light">Register</span></a
  >
</li>
{% endblock links %} 

{% block content %}
<div class="d-flex flex-column align-items-center my-auto py-4">
  {% if messages %} 
    {% for message in messages %}
      <div class="card">
        <p class="card-body text-center mb-0">{{ message }}</p>
      </div>
    {% endfor %} 
  {% endif %}
  <main class="form-signin w-100 m-auto">
    <form method="POST">
      {% csrf_token %}
      <h1 class="h3 mb-3 fw-bold">Please Login</h1>

      <div class="form-floating">
        <input
          type="text"
          class="form-control"
          id="floatingInput"
          placeholder="restuaar"
          name="username"
          autofocus
        />
        <label for="floatingInput">Username</label>
      </div>

      <div class="form-floating">
        <input
          type="password"
          class="form-control"
          id="floatingPassword"
          placeholder="password"
          name="password"
        />
        <label for="floatingPassword">Password</label>
      </div>

      <button
        class="btn btn-dark w-100 py-2"
        type="submit"
      >
        Login
      </button>
    </form>
  </main>
</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %} 
{% block title %} KoleksiKu | Book Collection {%endblock title %} 

{% block links %}
<li class="nav-item">
  <a
    class="nav-link active"
    href="{% url 'main:logout' %}"
    ><span class="border-bottom border-light">Logout</span></a
  >
</li>
<li class="nav-item">
  <p class="navbar-text mb-0">
    <span class="text-light me-2 ps-2 border-start border-light"
      >Welcome, {{ user }}</span
    >
  </p>
</li>
<li class="nav-item">
  <a
    class="nav-link active"
    href="{% url 'main:show_main' %}"
    ><span class="border-bottom border-light">KoleksiKu</span></a
  >
</li>
<li class="nav-item">
  <button
    type="button"
    data-bs-toggle="modal"
    data-bs-target="#modalAdd"
    class="nav-link active"
  >
    <span class="border-bottom border-light">Tambah Buku</span>
  </button>
</li>
{% endblock links %} 

{% block content %}
<div class="album pb-5 pt-3">
  <div class="card w-50 mb-3 mx-auto container-notif-buku-baru">
    <p class="card-body text-center mb-0 notif-buku-baru">
      <!-- Notif buku baru -->
    </p>
  </div>
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 bookshelf">
      <!-- Tempat Buku -->
    </div>
  </div>
</div>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %} 

{% block title %} Register | Book Collection {%endblock title %} 

{% block links %}
<li class="nav-item">
  <a
    class="nav-link active"
    href="{% url 'main:show_landing_page' %}"
    ><span class="border-bottom border-light">Home</span></a
  >
</li>
<li class="nav-item">
  <a
    class="nav-link active"
    href="{% url 'main:login' %}"
    ><span class="border-bottom border-light">Login</span></a
  >
</li>
{% endblock links %} 

{% block content %}
<div
  class="container-fluid d-flex flex-column justify-content-center align-items-center"
>
  <h2 class="fw-bold my-4">Register</h2>

  <form method="POST">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
      <tr>
        <td></td>
        <td>
          <button
            type="submit"
            class="btn btn-dark"
          >
            Submit
          </button>
        </td>
      </tr>
    </table>
  </form>

  {% if messages %}
  <ul>
    {% for message in messages %}
      <li>{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %}
</div>
{% endblock content %}

main/templates/tambah_buku.html
{% extends 'base.html' %} 

{% block title %} Tambah | Book Collection{% endblock title%} 

{% block content %}
<div class="py-4 text-center">
  <h2 class="fw-bold">Tambah Buku</h2>
</div>
<div class="container-form card p-5 text-bg-light">
  <form
    method="POST"
    class="row g-3"
  >
    {% csrf_token %}

    <div class="mb-3">
      <label
        class="form-label"
        for="name"
        >Name :</label
      >
      <input
        type="text"
        id="name"
        name="name"
        class="form-control"
        placeholder="Title here..."
        required
				autofocus
      />
    </div>
    <div class="mb-3">
      <label
        class="form-label"
        for="description"
        >Description :</label
      >
      <textarea
        class="form-control"
        name="description"
        row="3"
        placeholder="Description here..."
        required
      ></textarea>
    </div>
    <div class="d-flex justify-content-between">
      <div>
        <label
          class="form-label"
          for="amount"
          >Amount :</label
        >
        <input
          type="number"
          id="amount"
          name="amount"
          class="form-control"
          required
        />
      </div>
      <div class="align-self-end">
        <button
          type="submit"
          class="btn btn-dark"
        >
          Submit
        </button>
      </div>
    </div>
  </form>
</div>
{% endblock %}